
package pl.pkarpik.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloServiceImplService", targetNamespace = "http://impl.webservice.pkarpik.pl/", wsdlLocation = "http://localhost:8080/jaxws/helloService?wsdl")
public class HelloServiceImplService
    extends Service
{

    private final static URL HELLOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(pl.pkarpik.webservice.client.HelloServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = pl.pkarpik.webservice.client.HelloServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/jaxws/helloService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/jaxws/helloService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public HelloServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloServiceImplService() {
        super(HELLOSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://impl.webservice.pkarpik.pl/", "HelloServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "HelloServiceImplPort")
    public HelloService getHelloServiceImplPort() {
        return super.getPort(new QName("http://impl.webservice.pkarpik.pl/", "HelloServiceImplPort"), HelloService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "HelloServiceImplPort")
    public HelloService getHelloServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice.pkarpik.pl/", "HelloServiceImplPort"), HelloService.class, features);
    }

}
